Repository Namgyu-The-Best-Cat/Delivery, pull requests merged in 2024-11, with the labels that each got.

#3 #2 feat: create Review & Menu Entity
  src/main/java/com/bestcat/delivery/ai/entity/AiLog.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
  src/main/java/com/bestcat/delivery/review/entity/ReviewPhoto.java
Labels: feat, help wanted

#5 [FEAT] BaseEntity 생성 및 유저 Entity, RoleType 작성
  .gitignore
  src/main/java/com/bestcat/delivery/ai/entity/AiLog.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
  src/main/java/com/bestcat/delivery/review/entity/ReviewPhoto.java
  src/main/java/com/bestcat/delivery/user/entity/RoleType.java
  src/main/java/com/bestcat/delivery/user/entity/User.java
Labels: feat

#7 Area, Category, Store Entity 생성
  src/main/java/com/bestcat/delivery/area/entity/Area.java
  src/main/java/com/bestcat/delivery/category/entity/Category.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
  src/main/java/com/bestcat/delivery/store/entity/Store.java
  src/main/java/com/bestcat/delivery/store/entity/StoreCategory.java
Labels: feat

#14 [FEAT] #6, #11, #13 security 설정 추가, signin & signup 추가, BaseEntity createdBy, updatedBy 설정 추가
  build.gradle
  src/main/java/com/bestcat/delivery/common/config/AuditorAwareImpl.java
  src/main/java/com/bestcat/delivery/common/config/JpaConfig.java
  src/main/java/com/bestcat/delivery/common/config/PasswordEncoderConfig.java
  src/main/java/com/bestcat/delivery/common/config/WebSecurityConfig.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/common/util/JwtAuthenticationFilter.java
  src/main/java/com/bestcat/delivery/common/util/JwtAuthorizationFilter.java
  src/main/java/com/bestcat/delivery/common/util/JwtUtil.java
  src/main/java/com/bestcat/delivery/common/util/UserDetailsImpl.java
  src/main/java/com/bestcat/delivery/common/util/UserDetailsServiceImpl.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/order/entity/Order.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
  src/main/java/com/bestcat/delivery/review/entity/ReviewPhoto.java
  src/main/java/com/bestcat/delivery/store/entity/Store.java
  src/main/java/com/bestcat/delivery/user/dto/SigninRequestDto.java
  src/main/java/com/bestcat/delivery/user/dto/SignupRequestDto.java
  src/main/java/com/bestcat/delivery/user/repository/UserRepository.java
  src/main/java/com/bestcat/delivery/user/service/UserService.java
  src/main/java/com/bestcat/delivery/user/web/UserController.java
  src/main/resources/application.yml
Labels: feat, chore

#20 [Chore] add global exception
  src/main/java/com/bestcat/delivery/common/dto/ErrorResponse.java
  src/main/java/com/bestcat/delivery/common/dto/SuccessResponse.java
  src/main/java/com/bestcat/delivery/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bestcat/delivery/common/exception/RestApiException.java
  src/main/java/com/bestcat/delivery/common/type/ErrorCode.java
  src/main/java/com/bestcat/delivery/common/type/ResponseMessage.java
  src/main/java/com/bestcat/delivery/common/util/JwtAuthenticationFilter.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/user/dto/UserInfoDto.java
  src/main/java/com/bestcat/delivery/user/web/UserController.java
Labels: chore

#17 Feat/review
  build.gradle
  src/main/java/com/bestcat/delivery/common/config/S3Config.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/common/util/FileUpload.java
  src/main/java/com/bestcat/delivery/menu/dto/MenuRequestDto.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/order/entity/Order.java
  src/main/java/com/bestcat/delivery/review/dto/ReviewRequestDto.java
  src/main/java/com/bestcat/delivery/review/dto/ReviewResponseDto.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
  src/main/java/com/bestcat/delivery/review/entity/ReviewPhoto.java
  src/main/java/com/bestcat/delivery/review/repository/ReviewPhotoRepository.java
  src/main/java/com/bestcat/delivery/review/repository/ReviewRepository.java
  src/main/java/com/bestcat/delivery/review/service/ReviewPhotoService.java
  src/main/java/com/bestcat/delivery/review/service/ReviewService.java
  src/main/java/com/bestcat/delivery/review/web/ReviewApiController.java
Labels: feat

#22 19 feat category api 기능 구현
  src/main/java/com/bestcat/delivery/area/dto/AreaRequestDto.java
  src/main/java/com/bestcat/delivery/area/dto/AreaResponseDto.java
  src/main/java/com/bestcat/delivery/area/entity/Area.java
  src/main/java/com/bestcat/delivery/area/repository/AreaRepository.java
  src/main/java/com/bestcat/delivery/area/service/AreaService.java
  src/main/java/com/bestcat/delivery/area/web/AreaController.java
  src/main/java/com/bestcat/delivery/category/dto/CategoryRequestDto.java
  src/main/java/com/bestcat/delivery/category/dto/CategoryResponseDto.java
  src/main/java/com/bestcat/delivery/category/entity/Category.java
  src/main/java/com/bestcat/delivery/category/repository/CategoryRepository.java
  src/main/java/com/bestcat/delivery/category/service/CategoryService.java
  src/main/java/com/bestcat/delivery/category/web/CategoryController.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
Labels: feat

#18 Feat/area api 기능 추가
  src/main/java/com/bestcat/delivery/area/dto/AreaResponseDto.java
  src/main/java/com/bestcat/delivery/area/service/AreaService.java
  src/main/java/com/bestcat/delivery/area/web/AreaController.java
  src/main/java/com/bestcat/delivery/review/entity/Review.java
Labels: feat

#24 [FEAT] 유저 관련 기능 추가 및 리팩터링
  src/main/java/com/bestcat/delivery/common/config/WebSecurityConfig.java
  src/main/java/com/bestcat/delivery/common/dto/SuccessResponse.java
  src/main/java/com/bestcat/delivery/common/entity/BaseEntity.java
  src/main/java/com/bestcat/delivery/common/type/ErrorCode.java
  src/main/java/com/bestcat/delivery/common/type/ResponseMessage.java
  src/main/java/com/bestcat/delivery/common/util/CustomLogoutHandler.java
  src/main/java/com/bestcat/delivery/common/util/JwtAuthenticationFilter.java
  src/main/java/com/bestcat/delivery/common/util/JwtUtil.java
  src/main/java/com/bestcat/delivery/common/util/UserDetailsServiceImpl.java
  src/main/java/com/bestcat/delivery/review/repository/ReviewRepository.java
  src/main/java/com/bestcat/delivery/review/service/ReviewService.java
  src/main/java/com/bestcat/delivery/user/dto/NicknameRequestDto.java
  src/main/java/com/bestcat/delivery/user/dto/PasswordRequestDto.java
  src/main/java/com/bestcat/delivery/user/entity/User.java
  src/main/java/com/bestcat/delivery/user/repository/UserRepository.java
  src/main/java/com/bestcat/delivery/user/service/UserService.java
  src/main/java/com/bestcat/delivery/user/web/AuthController.java
  src/main/java/com/bestcat/delivery/user/web/UserController.java
Labels: feat, chore

#32 #23 [FEAT] Menu API 개발
  src/main/java/com/bestcat/delivery/common/util/FileUpload.java
  src/main/java/com/bestcat/delivery/menu/dto/MenuRequestDto.java
  src/main/java/com/bestcat/delivery/menu/dto/MenuResponseDto.java
  src/main/java/com/bestcat/delivery/menu/entity/Menu.java
  src/main/java/com/bestcat/delivery/menu/repository/MenuRepository.java
  src/main/java/com/bestcat/delivery/menu/service/MenuService.java
  src/main/java/com/bestcat/delivery/menu/web/MenuApiController.java
  src/main/java/com/bestcat/delivery/review/service/ReviewPhotoService.java
  src/main/java/com/bestcat/delivery/review/web/ReviewApiController.java
Labels: feat

#36 Fix deletAt and fix order query
  src/main/java/com/bestcat/delivery/menu/repository/MenuRepository.java
  src/main/java/com/bestcat/delivery/menu/service/MenuService.java
  src/main/java/com/bestcat/delivery/order/repository/OrderRepository.java
Labels: bug

#37 fix : orderItems 연관관계 추가
  src/main/java/com/bestcat/delivery/order/repository/OrderRepository.java
Labels: bug

#40 CI/CD 세팅 Actions
  .github/workflows/gradle.yml
Labels: chore

#42 CI/CD yml파일 수정 및 Dockerfile 생성
  Dockerfile
  src/main/resources/application.yml
Labels: chore

#44 [FEAT] MASTER, MANAGER 유저의 일반 유저 조회
  .gitignore
  build.gradle
  src/main/java/com/bestcat/delivery/common/config/JpaConfig.java
  src/main/java/com/bestcat/delivery/common/config/WebSecurityConfig.java
  src/main/java/com/bestcat/delivery/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bestcat/delivery/user/dto/UserDetailsInfoDto.java
  src/main/java/com/bestcat/delivery/user/dto/UserInfoDto.java
  src/main/java/com/bestcat/delivery/user/entity/SortType.java
  src/main/java/com/bestcat/delivery/user/repository/UserCustomRepository.java
  src/main/java/com/bestcat/delivery/user/repository/UserRepository.java
  src/main/java/com/bestcat/delivery/user/repository/UserRepositoryImpl.java
  src/main/java/com/bestcat/delivery/user/service/AdminService.java
  src/main/java/com/bestcat/delivery/user/service/UserService.java
  src/main/java/com/bestcat/delivery/user/web/AdminController.java
  src/main/java/com/bestcat/delivery/user/web/UserController.java
Labels: feat, chore

#47 [FIX] 에러 공통양식 적용, 임시 주석처리 TODO 리스트 수정 완료
  src/main/java/com/bestcat/delivery/ai/service/AiService.java
  src/main/java/com/bestcat/delivery/common/type/ErrorCode.java
  src/main/java/com/bestcat/delivery/menu/dto/MenuRequestDto.java
  src/main/java/com/bestcat/delivery/menu/service/MenuService.java
  src/main/java/com/bestcat/delivery/review/dto/ReviewResponseDto.java
  src/main/java/com/bestcat/delivery/review/service/ReviewService.java
Labels: refactor

#49 [FEAT] Review API 동작 수행 시 Store의 리뷰수, 평점 변경기능
  src/main/java/com/bestcat/delivery/review/service/ReviewService.java
  src/main/java/com/bestcat/delivery/store/entity/Store.java
Labels: feat
